-- MySQL Script generated by MySQL Workbench
-- Sun Aug 28 18:48:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinica_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clinica_DB` ;

-- -----------------------------------------------------
-- Schema clinica_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica_DB` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `clinica_DB` ;

-- -----------------------------------------------------
-- Table `categoria_med`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categoria_med` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categoria_med` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria_nome` VARCHAR(45) NOT NULL COMMENT 'Generalista/Especialista/Residente',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `consulta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consulta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `consulta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paciente_id` INT NOT NULL,
  `medico_id` INT NOT NULL,
  `especialidade_id` INT NULL,
  `categoria_id` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `valor` DECIMAL NOT NULL,
  `convenio_id` INT NULL,
  `carteirinha` INT NULL,
  `receita_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `convenio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `convenio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `convenio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `convenio_nome` VARCHAR(45) NOT NULL,
  `carencia` VARCHAR(45) NOT NULL,
  `cnpj` BIGINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `enfermagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enfermagem` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enfermagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `cpf` BIGINT NOT NULL,
  `cre` BIGINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `especialidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `especialidade` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `especialidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `especialidade_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `internacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internacao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `internacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_entrada` DATE NOT NULL,
  `data_prev_alta` DATE NOT NULL,
  `data_alta` DATE NOT NULL,
  `procedimentos` VARCHAR(200) NOT NULL,
  `id_quarto` INT NOT NULL,
  `id_enfermagem` INT NOT NULL,
  `id_paciente` INT NOT NULL,
  `id_medico` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `medicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `medicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nascimento` DATE NOT NULL,
  `cpf` BIGINT NOT NULL,
  `crm` BIGINT NOT NULL,
  `categoria_id` INT NOT NULL,
  `especialidade_id` INT NOT NULL,
  `telefone` BIGINT NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pacientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pacientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rg` INT NOT NULL,
  `cpf` BIGINT NOT NULL,
  `nascimento` DATE NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `convenio_id` INT NULL,
  `pacientescol` INT NULL,
  `carteirinha` INT NULL,
  `pacientescol1` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `quarto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quarto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `quarto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quartoNum` INT NOT NULL,
  `id_tipo` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `receitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `receitas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `receitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `consulta_id` INT NOT NULL,
  `paciente_id` INT NOT NULL,
  `medico_id` INT NOT NULL,
  `medicamento` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `duracao_dias` INT NOT NULL,
  `observacoes` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tipo_quarto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_quarto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipo_quarto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(15) NOT NULL,
  `valor_diario` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
